version: '3.4'

services:
  mysql:
    image: mysql:5.7.28
    container_name: mysql.test.api
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT_OUT}:3306"
    volumes:
      - "../mysql/conf:/etc/mysql/conf.d"
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --collation-server=utf8mb4_unicode_ci --explicit_defaults_for_timestamp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.test.api
    links:
      - mysql:db
    ports:
      - "${PHPMYADMIN_PORT_OUT}:80"
