spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:23306/db?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: admin
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    maxActive: 20
    maxWait: 20000
    poolPreparedStatements: true
    maxOpenPreparedStatements: 1
    testWhileIdle: true
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
    database-platform: MYSQL
server:
  port: 8080
